/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "ng-bg":          "var(--color-bg)",
        "ng-surface":     "var(--color-surface)",
        "ng-border":      "var(--color-border)",
        "ng-primary":     "var(--color-text-primary)",
        "ng-secondary":   "var(--color-text-secondary)",
        "ng-disabled":    "var(--color-text-disabled)",
        "ng-accent":      "var(--color-accent)",
        "ng-accent-hov":  "var(--color-accent-hover)",
        "ng-accent-lit":  "var(--color-accent-light)",
        "ng-accent-fg":   "var(--color-accent-fg)",
        "ng-success":     "var(--color-success)",
        "ng-success-bg":  "var(--color-success-bg)",
        "ng-success-bd":  "var(--color-success-border)",
        "ng-success-tx":  "var(--color-success-text)",
        "ng-warning":     "var(--color-warning)",
        "ng-warning-bg":  "var(--color-warning-bg)",
        "ng-warning-bd":  "var(--color-warning-border)",
        "ng-warning-tx":  "var(--color-warning-text)",
        "ng-danger":      "var(--color-danger)",
        "ng-danger-bg":   "var(--color-danger-bg)",
        "ng-danger-bd":   "var(--color-danger-border)",
        "ng-danger-tx":   "var(--color-danger-text)",
        "ng-info-bg":     "var(--color-info-bg)",
        "ng-info-tx":     "var(--color-info-text)",
        "ng-muted":       "var(--color-muted-bg)",
        "ng-muted-bd":    "var(--color-muted-border)",
        "ng-muted-tx":    "var(--color-muted-text)",
        "ng-row-alt":     "var(--color-row-alt)",
        "ng-well":        "var(--color-bg)",
        "chart-1":        "var(--chart-1)",
        "chart-2":        "var(--chart-2)",
        "chart-3":        "var(--chart-3)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["SF Mono", "Consolas", "Fira Code", "monospace"],
      },
      fontSize: {
        "ng-2xs":  "10px",
        "ng-xs":   "11px",
        "ng-sm":   "13px",
        "ng-base": "14px",
        "ng-lg":   "16px",
        "ng-2xl":  "24px",
        "ng-hero": "32px",
      },
      boxShadow: {
        "ng-xs": "var(--shadow-xs)",
        "ng-sm": "var(--shadow-sm)",
        "ng-md": "var(--shadow-md)",
      },
    },
  },
  plugins: [],
};
