/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "ng-bg":          "var(--color-bg)",
        "ng-surface":     "var(--color-surface)",
        "ng-raised":      "var(--color-surface-raised)",
        "ng-border":      "var(--color-border)",
        "ng-primary":     "var(--color-text-primary)",
        "ng-secondary":   "var(--color-text-secondary)",
        "ng-disabled":    "var(--color-text-disabled)",
        "ng-accent":      "var(--color-accent)",
        "ng-accent-hov":  "var(--color-accent-hover)",
        "ng-accent-lit":  "var(--color-accent-light)",
        "ng-accent-fg":   "var(--color-accent-fg)",
        "ng-success":     "var(--color-success)",
        "ng-success-bg":  "var(--color-success-bg)",
        "ng-success-bd":  "var(--color-success-border)",
        "ng-success-tx":  "var(--color-success-text)",
        "ng-warning":     "var(--color-warning)",
        "ng-warning-bg":  "var(--color-warning-bg)",
        "ng-warning-bd":  "var(--color-warning-border)",
        "ng-warning-tx":  "var(--color-warning-text)",
        "ng-danger":      "var(--color-danger)",
        "ng-danger-bg":   "var(--color-danger-bg)",
        "ng-danger-bd":   "var(--color-danger-border)",
        "ng-danger-tx":   "var(--color-danger-text)",
        "ng-info":        "var(--color-info)",
        "ng-info-bg":     "var(--color-info-bg)",
        "ng-info-bd":     "var(--color-info-border)",
        "ng-info-tx":     "var(--color-info-text)",
        "ng-ai":          "var(--color-ai)",
        "ng-ai-bg":       "var(--color-ai-bg)",
        "ng-ai-bd":       "var(--color-ai-border)",
        "ng-ai-tx":       "var(--color-ai-text)",
        "ng-muted":       "var(--color-muted-bg)",
        "ng-muted-bd":    "var(--color-muted-border)",
        "ng-muted-tx":    "var(--color-muted-text)",
        "ng-row-alt":     "var(--color-row-alt)",
        "ng-well":        "var(--color-bg)",

        // Control-loop phases — a phase scale, never a data-series identity.
        "phase-perceive":    "var(--phase-perceive)",
        "phase-perceive-bg": "var(--phase-perceive-bg)",
        "phase-perceive-tx": "var(--phase-perceive-tx)",
        "phase-reason":      "var(--phase-reason)",
        "phase-reason-bg":   "var(--phase-reason-bg)",
        "phase-reason-tx":   "var(--phase-reason-tx)",
        "phase-plan":        "var(--phase-plan)",
        "phase-plan-bg":     "var(--phase-plan-bg)",
        "phase-plan-tx":     "var(--phase-plan-tx)",
        "phase-execute":     "var(--phase-execute)",
        "phase-execute-bg":  "var(--phase-execute-bg)",
        "phase-execute-tx":  "var(--phase-execute-tx)",
        "phase-recover":     "var(--phase-recover)",
        "phase-recover-bg":  "var(--phase-recover-bg)",
        "phase-recover-tx":  "var(--phase-recover-tx)",

        "chart-1":        "var(--chart-1)",
        "chart-2":        "var(--chart-2)",
        "chart-3":        "var(--chart-3)",
        "chart-4":        "var(--chart-4)",
        "chart-5":        "var(--chart-5)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        mono: ["SF Mono", "Consolas", "Fira Code", "monospace"],
      },
      fontSize: {
        "ng-2xs":  "10px",
        "ng-xs":   "11px",
        "ng-sm":   "13px",
        "ng-base": "14px",
        "ng-lg":   "16px",
        "ng-2xl":  "24px",
        "ng-hero": "32px",
      },
      boxShadow: {
        "ng-xs": "var(--shadow-xs)",
        "ng-sm": "var(--shadow-sm)",
        "ng-md": "var(--shadow-md)",
      },
      spacing: {
        // The two sidebar widths, so the shell and its spacer never drift.
        "rail": "60px",
        "sidebar": "240px",
      },
    },
  },
  plugins: [],
};
